name: Run cfn-lint on CFN template

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install cfn-lint
        run: python3 -m pip install -r dev.requirements.txt
      - name: Run cfn-lint against template.yaml
        run: cfn-lint -t template.yaml
